---
name: macOS build

on:
  push:
    branches: [master]
    paths-ignores:
      - '**.md'
      - '.github/workflows/build.yml'

  pull_request:
    branches: [master]

jobs:
  macOS12:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '18.0.2'
      - name: Install required Packages
        run: sudo apt install -y make tree git wget coreutils
      - name: Check JAVA configuration    
        run: |
          which java
          which mvn
      - name: Configuration
        run: |
          make init
          echo "JAVA_HOME:=${JAVA_HOME}"      > configure/CONFIG_COMMON.local
          echo "JAVA_PATH:=${JAVA_HOME}/bin" >> configure/CONFIG_COMMON.local
          echo "MAVEN_HOME:=/usr"            >> configure/CONFIG_COMMON.local
          echo "MAVEN_PATH:=/usr/bin"        >> configure/CONFIG_COMMON.local
          make patch
          make conf.macos
      - name: Build Phoebus
        run: |
          make build.phoebus
          make prop.phoebus
          make install.phoebus
      - name: Build Application
        run: |
          make dmgapp
          make zipapp
          make tarapp
      - name: Environment Check
        run: |
          make exist
          ls -ltah
