# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Phoebus and Alarm Trio Build Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11.0.x'
        java-package: jdk
        architecture: x64
    - run: |
        java -version
        echo $JAVA_HOME
        echo $PATH
        mvn --version
    - run: sudo apt-get install tree openjfx libopenjfx-java
    - run: |
        make init
        make patch
        make vars
    - run: |
        make build.phoebus
        make prop.phoebus
        make install.phoebus
    - run: |
        make build
        make sd_config
        make install
    - run: make exist
    - run:
        bash scripts/build_test.sh all        
                
        
